apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testing-service
  description: resideo
  namespace: engineering-portal
  # Example for optional annotations
  annotations:
    github.com/project-slug: resideo/testing-service
    backstage.io/techdocs-ref: github:https://github.com/resideo/testing-service.git
spec:
  type: service
  owner: resideo
  lifecycle: experimental
  providesApis:
    - testing-service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: testing-service
  description: testing-service OpenAPI
  namespace: engineering-portal
  tags:
    - openapi
    - rest
    - ceres
spec:
  type: openapi
  lifecycle: experimental
  owner: "@resideo/ceres"
  definition:
    $text: ./openapi.yaml
---
