#
# These values are used with https://github.com/resideo/dpl-microservice-helm/ chart
# See repository for full list of available values
#
logging:
  enabled: false

livenessProbe:
  enabled: true
  path: "/healthz"

readinessProbe:
  enabled: true
  path: "/readyz"
